#!/bin/bash

model_name=iTransformer

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 512 \
  --train_epochs 10 \
  --d_ff 512 \
  --itr 1 \
  --lradj 'type1' \
  --learning_rate 0.005 \
  --batch_size 512 \
  --use_rag \
  --gemma_1 1.0 \
  --gemma_2 0.0 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 512 \
  --train_epochs 10 \
  --d_ff 512 \
  --itr 1 \
  --lradj 'type1' \
  --n_heads 1 \
  --learning_rate 0.005 \
  --batch_size 512 \
  --use_rag \
  --gemma_1 1.0 \
  --gemma_2 0.1 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 512 \
  --train_epochs 10 \
  --d_ff 512 \
  --itr 1 \
  --lradj 'type1' \
  --n_heads 1 \
  --learning_rate 0.005 \
  --batch_size 512 \
  --use_rag \
  --gemma_1 1.0 \
  --gemma_2 0.5 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 512 \
  --train_epochs 10 \
  --d_ff 512 \
  --itr 1 \
  --lradj 'type1' \
  --n_heads 1 \
  --learning_rate 0.005 \
  --batch_size 512 \
  --use_rag \
  --gemma_1 1.0 \
  --gemma_2 1.0 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 512 \
  --train_epochs 10 \
  --d_ff 512 \
  --itr 1 \
  --lradj 'type1' \
  --n_heads 1 \
  --learning_rate 0.005 \
  --batch_size 512 \
  --use_rag \
  --gemma_1 1.0 \
  --gemma_2 5.0 \