#!/bin/bash
# Shard any b*.sh campaign across several GPUs, resumably.
#
# The b*.sh scripts are serial: one run at a time on one GPU. That is why a full
# campaign reads as "2-4 GPU-days" -- it is 320 runs in a single queue. This wrapper
# takes the exact same command list (generated by DRY_RUN=1, so there is one source
# of truth for the configs) and runs it N-wide, one worker per GPU.
#
# Every command gets --skip_if_done, so re-running skips completed work: safe to
# interrupt, safe to relaunch, safe to add GPUs later.
#
# Usage
#   GPUS="1 2 3" bash scripts/craft_rebuttal/parallel.sh \
#       "SCOPE=full bash scripts/craft_rebuttal/b2_main_multiseed.sh"
#
#   # inspect the queue without running anything
#   GPUS="1 2" PLAN_ONLY=1 bash scripts/craft_rebuttal/parallel.sh "SCOPE=full bash ..."
set -u

GPUS=${GPUS:-"0"}
GEN=${1:?usage: GPUS=\"1 2 3\" parallel.sh \"<DRY_RUN-able generator command>\"}
QUEUE=${QUEUE:-analysis/queue.txt}
LOGDIR=${LOGDIR:-logs}
PLAN_ONLY=${PLAN_ONLY:-0}

mkdir -p "$(dirname "$QUEUE")" "$LOGDIR" runs analysis

echo "### generating the queue"
# DRY_RUN=1 makes run_one echo its command instead of executing it.
DRY_RUN=1 eval "$GEN" 2>/dev/null | grep -E "run\.py" > "$QUEUE"
TOTAL=$(wc -l < "$QUEUE")
if [ "$TOTAL" -eq 0 ]; then
  echo "queue is empty -- does the generator honour DRY_RUN?"; exit 1
fi

read -r -a GPU_ARR <<< "$GPUS"
N=${#GPU_ARR[@]}
echo "### $TOTAL runs across $N GPU(s): ${GPUS}"
echo "### est. wall clock = serial_time / $N  (round-robin sharding)"

if [ "$PLAN_ONLY" = "1" ]; then
  echo "--- first 3 commands ---"
  head -3 "$QUEUE" | cut -c1-200
  awk '{ for(i=1;i<=NF;i++) if($i=="--data_path") print $(i+1) }' "$QUEUE" \
    | sort | uniq -c | sort -rn | sed 's/^/    /'
  exit 0
fi

START=$(date +%s)
for i in $(seq 0 $((N - 1))); do
  G=${GPU_ARR[$i]}
  SHARD="$QUEUE.shard$G"
  # Round-robin so the heavy datasets spread across workers rather than piling
  # onto one. Not a true load balance; good enough and fully deterministic.
  awk -v n="$N" -v i="$i" 'NR % n == i' "$QUEUE" > "$SHARD"
  COUNT=$(wc -l < "$SHARD")
  echo "  gpu $G: $COUNT runs -> $SHARD"
  (
    k=0
    while IFS= read -r cmd; do
      k=$((k + 1))
      # Retarget the GPU and make the run resumable.
      cmd=$(echo "$cmd" | sed -E "s/--gpu [0-9]+/--gpu $G/")
      cmd="$cmd --skip_if_done"
      LOG="$LOGDIR/gpu${G}_$(printf '%04d' $k).log"
      echo "[gpu$G $k/$COUNT] $(date +%H:%M:%S)"
      if ! eval "$cmd" > "$LOG" 2>&1; then
        echo "[gpu$G $k/$COUNT] FAILED -> $LOG"
      fi
    done < "$SHARD"
    echo "[gpu$G] done"
  ) &
done

wait
ELAPSED=$(( $(date +%s) - START ))
echo "### all workers finished in $((ELAPSED / 60)) min"

DONE=$(ls runs/*.json 2>/dev/null | wc -l)
echo "### run records: $DONE"
FAILS=$(grep -rl "Traceback" "$LOGDIR" 2>/dev/null | wc -l)
[ "$FAILS" -gt 0 ] && echo "### $FAILS log(s) contain a traceback -- inspect before aggregating"
echo "### next: python experiments/aggregate_results.py --runs runs --out analysis"
